apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: web
  name: client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - image: anbinhtrong/hostingmvc
        name: client
        imagePullPolicy: Always
        ports:
          - containerPort: 80