apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: web
  name: client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-app
  template:
    metadata:
      labels:
        app: client-app
    spec:
      containers:
      - image: anbinhtrong/hostingmvc
        name: client-app
        imagePullPolicy: Always
        ports:
          - containerPort: 80